# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Run Simulation
  jobs:  
  - job: Test
    displayName: Test
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Bash@3
      inputs:
        filePath: '/jargo/run_example_ny.sh'
