name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.1'
    - name: get deps
      run: ./getdeps.sh
    - name: make jar
      run: make jar


