name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install javafx
      run: sudo apt install openjdk-11-jdk openjfx
    - name: make jar
      run: make jar
